# Generated by Django 5.0.6 on 2024-05-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officersHome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newofficerregistration',
            name='officer_stationRank',
            field=models.CharField(choices=[('DC', 'District Commander'), ('DIVC', 'Divisional Commander'), ('SO', 'Station Officer'), ('DSO', 'Deputy Station Officer'), ('SSI', 'Station Sergeants and Inspector'), ('OO', 'Other Officer/Constables')], default=250, max_length=100),
            preserve_default=False,
        ),
    ]
