# Generated by Django 5.0.6 on 2024-05-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officersHome', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
