# Generated by Django 5.0.6 on 2024-05-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officersHome', '0003_officerstationgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newofficerregistration',
            name='officer_Operationsdistrict',
            field=models.CharField(choices=[('GA', 'Greater Accra'), ('AR', 'Ahafo Region'), ('ARR', 'Ashanti Region'), ('BR', 'Bono Region'), ('BER', 'Bono East Region'), ('CR', 'Central Region'), ('ER', 'Eastern Region'), ('NER', 'North East Region'), ('NR', 'Northern Region'), ('OR', 'Oti Region'), ('SR', 'Savannah Region'), ('UER', 'Upper East Region'), ('UWR', 'Upper West Region'), ('VR', 'Volta Region'), ('WR', 'Western Region'), ('WNR', 'Western North Region')], default=250, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newofficerregistration',
            name='officer_operations_region',
            field=models.CharField(choices=[('GA', 'Greater Accra'), ('AR', 'Ahafo Region'), ('ARR', 'Ashanti Region'), ('BR', 'Bono Region'), ('BER', 'Bono East Region'), ('CR', 'Central Region'), ('ER', 'Eastern Region'), ('NER', 'North East Region'), ('NR', 'Northern Region'), ('OR', 'Oti Region'), ('SR', 'Savannah Region'), ('UER', 'Upper East Region'), ('UWR', 'Upper West Region'), ('VR', 'Volta Region'), ('WR', 'Western Region'), ('WNR', 'Western North Region')], max_length=250),
        ),
    ]
