# Generated by Django 5.0.6 on 2024-05-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officersHome', '0004_newofficerregistration_officer_operationsdistrict_and_more'),
    ]


    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(choices=[('Case', 'Case Statement'), ('Victim', 'Victim'), ('VW', 'Victim Witness'), ('Suspect', 'Suspect'), ('SW', 'Suspect Witness')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('residential_address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('hometown', models.CharField(max_length=100)),
                ('occurrence', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='witness',
            name='target_ptr',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='target_ptr',
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_statement', to='officersHome.statement')),
                ('suspect_statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_statement', to='officersHome.statement')),
                ('victim_statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='victim_statement', to='officersHome.statement')),
            ],
        ),
        migrations.DeleteModel(
            name='Suspect',
        ),
        migrations.DeleteModel(
            name='Witness',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.DeleteModel(
            name='Victim',
        ),
    ]
