# Generated by Django 4.2.13 on 2024-08-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officersHome', '0004_rename_uploaded_at_pdfdocument_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=255)),
                ('date_time_of_incident', models.DateTimeField()),
                ('date_time_of_report', models.DateTimeField()),
                ('complainant_name', models.CharField(max_length=255)),
                ('complainant_contact', models.CharField(max_length=20)),
                ('complainant_physical_address', models.CharField(max_length=255)),
                ('complainant_digital_address', models.CharField(blank=True, max_length=255, null=True)),
                ('complainant_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('complainant_date_of_birth', models.DateField(blank=True, null=True)),
                ('suspect_name', models.CharField(blank=True, max_length=255, null=True)),
                ('suspect_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('suspect_physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('suspect_digital_address', models.CharField(blank=True, max_length=255, null=True)),
                ('suspect_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('suspect_date_of_birth', models.DateField(blank=True, null=True)),
                ('is_victim_same_as_complainant', models.BooleanField(default=True)),
                ('victim_name', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('victim_physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_digital_address', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('victim_date_of_birth', models.DateField(blank=True, null=True)),
                ('location_of_incident', models.CharField(max_length=255)),
                ('type_of_incident', models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Traffic Accident', 'Traffic Accident'), ('Other', 'Other')], max_length=100)),
                ('statement_of_incident', models.TextField()),
                ('key_witness_name', models.CharField(blank=True, max_length=255, null=True)),
                ('key_witness_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('key_witness_physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('key_witness_digital_address', models.CharField(blank=True, max_length=255, null=True)),
                ('complainant_statement', models.TextField()),
                ('suspect_statement', models.TextField()),
                ('witness_statement', models.TextField()),
                ('additional_witnesses', models.JSONField(blank=True, default=list)),
                ('reporting_officer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_officer_badge_id', models.CharField(blank=True, max_length=50, null=True)),
                ('reporting_officer_rank', models.CharField(blank=True, max_length=50, null=True)),
                ('reporting_officer_station', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_officer_division', models.CharField(blank=True, max_length=255, null=True)),
                ('charges_filed', models.TextField(blank=True, null=True)),
                ('legal_actions_taken', models.TextField(blank=True, null=True)),
                ('assigned_investigator', models.CharField(blank=True, max_length=255, null=True)),
                ('case_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Closed', 'Closed')], max_length=50, null=True)),
                ('follow_up_required', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('mugshot', models.FileField(blank=True, null=True, upload_to='mugshots/')),
                ('fingerprint', models.FileField(blank=True, null=True, upload_to='fingerprints/')),
            ],
        ),
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='user',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(default=255, upload_to='pdfs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='title',
            field=models.CharField(default=250, max_length=200),
            preserve_default=False,
        ),
    ]
