# Generated by Django 4.2.13 on 2024-08-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officersHome', '0005_case_rename_created_at_pdfdocument_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_title',
            new_name='Case_Title',
        ),
    ]
