# Generated by Django 5.0.6 on 2024-05-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officersHome', '0005_statement_remove_witness_target_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('residential_address', models.CharField(max_length=255)),
                ('gps', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('work_occupation', models.CharField(max_length=255)),
                ('placeOfWork', models.CharField(max_length=255)),
                ('hometown', models.CharField(max_length=255)),
                ('material_evidendence', models.FileField(upload_to='evidence/')),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('target_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='officersHome.target')),
                ('mugshot', models.ImageField(upload_to='mugshots/')),
                ('fingerprints', models.ImageField(upload_to='fingerprints/')),
                ('life_details', models.TextField()),
            ],
            bases=('officersHome.target',),
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('target_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='officersHome.target')),
            ],
            bases=('officersHome.target',),
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('target_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='officersHome.target')),
                ('relationship_to_witness', models.CharField(max_length=100)),
            ],
            bases=('officersHome.target',),
        ),
    ]
