# Generated by Django 5.0.6 on 2024-05-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officersHome', '0006_target_suspect_victim_witness'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statement',
            new_name='Statements',
        ),
    ]
